module.exports = [
	'animations',
	'document-write',
	'image-compression',
	'layout-animations',
	'legacy-image-formats',
	'max-downscaling-image',
	'notifications',
	'oversized-images',
	'push',
	'speaker',
	'unsized-media',
	'vibrate',
	'vr',
	'wake-lock',
	'webauthn',
	'web-share',
]
